title = 'Sundown Sessions'
languageCode = 'en-gb'
theme = 'ananke'








baseURL = 'https://example.org/'



[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/colingourlay"


[params]
text_color = ""
author = ""
favicon = ""
site_logo = ""
description = "The last theme you'll ever need. Maybe."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
recent_posts_number = 3

#[params]
#site_logo = "images/sundown-sessions-logo.jpg"

#twitter*
#instagram
#youtube
#github
#gitlab
#keybase
#medium
#mastodon
#slack
#stackoverflow
#facebook*
#rss