version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - github-actions
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: nuget
    directory: /automation/dotnet
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - dotnet
    groups:
      dotnet-dependencies:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /src/themes/sundown-sessions
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - hugo
    groups:
      npm-dependencies:
        patterns:
          - "*"
