[[footer]]
  identifier = "listen-again"
  name = "Listen Again"
  title = "Browse Sundown Sessions shows"
  url = "/shows/"
  weight = 10

[[footer]]
  identifier = "contact"
  name = "Contact"
  title = "Get in touch with the show."
  url = "/contact/"
  weight = 20
