favicon = "favicon.ico"

[[ananke_socials]]
name = "instagram"
url = ""

[[ananke_socials]]
name = "facebook"
url = "https://www.facebook.com/groups/sundownsessions"

[[ananke_socials]]
name = "twitter"
url = "https://twitter.com/sundown_session"

[[ananke_socials]]
name = "pinterest"
url = "https://www.pinterest.co.uk/pinterestvengeful637/sundown-sessions/"

[[ananke_socials]]
name = "tiktok"
url = "https://www.tiktok.com/@sundownsessionsshow"

[[ananke_socials]]
name = "mastodon"
url = "https://mastodon.scot/@sundown_sessions"

[[ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/colingourlay"

[[ananke_socials]]
name = "github"
url = "https://github.com/colin-gourlay/sundown-sessions/issues/new/choose"