[[ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/colingourlay"





[params.contact]
email = 'info@example.org'
phone = '+1 202-555-1212'






subtitle = 'The Best Widgets on Earth'
text_color = ""
author = ""
favicon = ""
site_logo = ""
description = "The last theme you'll ever need. Maybe."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
recent_posts_number = 3

#[params]
#site_logo = "images/sundown-sessions-logo.jpg"

#twitter*
#instagram
#youtube
#github
#gitlab
#keybase
#medium
#mastodon
#slack
#stackoverflow
#facebook*
#rss