// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SundownSessions.Showrunner.Persistence;

#nullable disable

namespace SundownSessions.Showrunner.Persistence.Migrations
{
    [DbContext(typeof(ShowrunnerDbContext))]
    [Migration("20260822113915_AddFinalisationHistoryOrdering")]
    partial class AddFinalisationHistoryOrdering
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("SundownSessions.Showrunner.Persistence.BacklogItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RecordingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecordingId");

                    b.ToTable("BacklogItems", (string)null);
                });

            modelBuilder.Entity("SundownSessions.Showrunner.Persistence.BroadcastRecordingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("BroadcastAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PlannedRecordingId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RecordingId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShowId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlannedRecordingId");

                    b.HasIndex("RecordingId");

                    b.HasIndex("ShowId", "PlannedRecordingId")
                        .IsUnique()
                        .HasFilter("\"PlannedRecordingId\" IS NOT NULL");

                    b.HasIndex("ShowId", "Position")
                        .IsUnique();

                    b.ToTable("BroadcastRecordings", null, t =>
                        {
                            t.HasCheckConstraint("CK_BroadcastRecordings_Position", "Position >= 1");
                        });
                });

            modelBuilder.Entity("SundownSessions.Showrunner.Persistence.ConfirmedPlaybackItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PlannedRecordingId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ReconciliationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecordingId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlannedRecordingId");

                    b.HasIndex("RecordingId");

                    b.HasIndex("ReconciliationId", "PlannedRecordingId")
                        .IsUnique()
                        .HasFilter("\"PlannedRecordingId\" IS NOT NULL");

                    b.HasIndex("ReconciliationId", "Position")
                        .IsUnique();

                    b.ToTable("ConfirmedPlaybackItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_ConfirmedPlaybackItems_Position", "Position >= 1");
                        });
                });

            modelBuilder.Entity("SundownSessions.Showrunner.Persistence.PlannedRecordingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RecordingId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShowId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecordingId");

                    b.HasIndex("ShowId", "Position")
                        .IsUnique();

                    b.ToTable("PlannedRecordings", null, t =>
                        {
                            t.HasCheckConstraint("CK_PlannedRecordings_Position", "Position >= 1");
                        });
                });

            modelBuilder.Entity("SundownSessions.Showrunner.Persistence.ReconciliationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ConfirmedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("OperatorConfirmedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShowId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShowId")
                        .IsUnique();

                    b.ToTable("Reconciliations", (string)null);
                });

            modelBuilder.Entity("SundownSessions.Showrunner.Persistence.ReconciliationItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Outcome")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PlannedRecordingId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReconciliationId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlannedRecordingId");

                    b.HasIndex("ReconciliationId", "PlannedRecordingId")
                        .IsUnique();

                    b.ToTable("ReconciliationItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_ReconciliationItems_Outcome", "Outcome IN (0, 1, 2)");
                        });
                });

            modelBuilder.Entity("SundownSessions.Showrunner.Persistence.RecordingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseTitle")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Recordings", (string)null);
                });

            modelBuilder.Entity("SundownSessions.Showrunner.Persistence.RecordingExternalIdentifierEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecordingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecordingId");

                    b.HasIndex("Source", "Value")
                        .IsUnique();

                    b.ToTable("RecordingExternalIdentifiers", (string)null);
                });

            modelBuilder.Entity("SundownSessions.Showrunner.Persistence.RepeatExceptionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecordingId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShowId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecordingId");

                    b.HasIndex("ShowId", "RecordingId")
                        .IsUnique();

                    b.ToTable("RepeatExceptions", (string)null);
                });

            modelBuilder.Entity("SundownSessions.Showrunner.Persistence.ShowEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ShowDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Shows", (string)null);
                });

            modelBuilder.Entity("SundownSessions.Showrunner.Persistence.BacklogItemEntity", b =>
                {
                    b.HasOne("SundownSessions.Showrunner.Persistence.RecordingEntity", null)
                        .WithMany()
                        .HasForeignKey("RecordingId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("SundownSessions.Showrunner.Persistence.BroadcastRecordingEntity", b =>
                {
                    b.HasOne("SundownSessions.Showrunner.Persistence.PlannedRecordingEntity", null)
                        .WithMany()
                        .HasForeignKey("PlannedRecordingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SundownSessions.Showrunner.Persistence.RecordingEntity", null)
                        .WithMany()
                        .HasForeignKey("RecordingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SundownSessions.Showrunner.Persistence.ShowEntity", "Show")
                        .WithMany("BroadcastRecordings")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Show");
                });

            modelBuilder.Entity("SundownSessions.Showrunner.Persistence.ConfirmedPlaybackItemEntity", b =>
                {
                    b.HasOne("SundownSessions.Showrunner.Persistence.PlannedRecordingEntity", null)
                        .WithMany()
                        .HasForeignKey("PlannedRecordingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SundownSessions.Showrunner.Persistence.ReconciliationEntity", "Reconciliation")
                        .WithMany("ConfirmedPlayback")
                        .HasForeignKey("ReconciliationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SundownSessions.Showrunner.Persistence.RecordingEntity", null)
                        .WithMany()
                        .HasForeignKey("RecordingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reconciliation");
                });

            modelBuilder.Entity("SundownSessions.Showrunner.Persistence.PlannedRecordingEntity", b =>
                {
                    b.HasOne("SundownSessions.Showrunner.Persistence.RecordingEntity", null)
                        .WithMany()
                        .HasForeignKey("RecordingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SundownSessions.Showrunner.Persistence.ShowEntity", "Show")
                        .WithMany("PlannedRecordings")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Show");
                });

            modelBuilder.Entity("SundownSessions.Showrunner.Persistence.ReconciliationEntity", b =>
                {
                    b.HasOne("SundownSessions.Showrunner.Persistence.ShowEntity", "Show")
                        .WithOne("Reconciliation")
                        .HasForeignKey("SundownSessions.Showrunner.Persistence.ReconciliationEntity", "ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Show");
                });

            modelBuilder.Entity("SundownSessions.Showrunner.Persistence.ReconciliationItemEntity", b =>
                {
                    b.HasOne("SundownSessions.Showrunner.Persistence.PlannedRecordingEntity", null)
                        .WithMany()
                        .HasForeignKey("PlannedRecordingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SundownSessions.Showrunner.Persistence.ReconciliationEntity", "Reconciliation")
                        .WithMany("Items")
                        .HasForeignKey("ReconciliationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reconciliation");
                });

            modelBuilder.Entity("SundownSessions.Showrunner.Persistence.RecordingExternalIdentifierEntity", b =>
                {
                    b.HasOne("SundownSessions.Showrunner.Persistence.RecordingEntity", "Recording")
                        .WithMany("ExternalIdentifiers")
                        .HasForeignKey("RecordingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recording");
                });

            modelBuilder.Entity("SundownSessions.Showrunner.Persistence.RepeatExceptionEntity", b =>
                {
                    b.HasOne("SundownSessions.Showrunner.Persistence.RecordingEntity", null)
                        .WithMany()
                        .HasForeignKey("RecordingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SundownSessions.Showrunner.Persistence.ShowEntity", null)
                        .WithMany()
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SundownSessions.Showrunner.Persistence.ReconciliationEntity", b =>
                {
                    b.Navigation("ConfirmedPlayback");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("SundownSessions.Showrunner.Persistence.RecordingEntity", b =>
                {
                    b.Navigation("ExternalIdentifiers");
                });

            modelBuilder.Entity("SundownSessions.Showrunner.Persistence.ShowEntity", b =>
                {
                    b.Navigation("BroadcastRecordings");

                    b.Navigation("PlannedRecordings");

                    b.Navigation("Reconciliation");
                });
#pragma warning restore 612, 618
        }
    }
}
