#!/usr/bin/env python3
"""Audit taxonomy-backed Release Details metadata and write a review report."""

from __future__ import annotations

import argparse
import re
from collections import Counter
from pathlib import Path

import yaml


ROOT = Path(__file__).parents[1]
DEFAULT_CONTENT = ROOT / "src/content/releases"
DEFAULT_REPORT = ROOT / "reports/release-metadata-audit.md"
FIELDS = {
    "labels": "label",
    "producers": "producer",
    "genres": "genre",
    "tags": None,
}


def front_matter(path: Path) -> dict:
    text = path.read_text(encoding="utf-8-sig")
    match = re.match(r"(?s)^---\s*\n(.*?)\n---(?:\s*\n|$)", text)
    if not match:
        return {}
    parsed = yaml.safe_load(match.group(1)) or {}
    return parsed if isinstance(parsed, dict) else {}


def has_values(value: object) -> bool:
    if isinstance(value, str):
        return bool(value.strip())
    if isinstance(value, (list, tuple)):
        return any(has_values(item) for item in value)
    return value is not None


def audit(content_root: Path) -> tuple[list[dict], list[str]]:
    releases: list[dict] = []
    errors: list[str] = []

    for path in sorted(content_root.rglob("index.md")):
        data = front_matter(path)
        try:
            relative = path.relative_to(ROOT).as_posix()
        except ValueError:
            relative = path.relative_to(content_root).as_posix()

        unavailable = data.get("releaseMetadataUnavailable") or []
        if isinstance(unavailable, str):
            unavailable = [unavailable]
        unavailable = {str(value).strip() for value in unavailable}
        unknown = unavailable.difference(FIELDS)
        if unknown:
            errors.append(
                f"{relative}: unknown releaseMetadataUnavailable fields: "
                f"{', '.join(sorted(unknown))}"
            )

        statuses: dict[str, str] = {}
        for canonical, legacy in FIELDS.items():
            canonical_present = canonical in data
            canonical_values = has_values(data.get(canonical))
            legacy_values = legacy is not None and has_values(data.get(legacy))
            if canonical_values:
                statuses[canonical] = "linkable"
            elif legacy_values:
                statuses[canonical] = "legacy"
            elif canonical_present:
                statuses[canonical] = "empty"
            elif canonical in unavailable:
                statuses[canonical] = "unavailable"
            else:
                statuses[canonical] = "missing"

        releases.append(
            {
                "path": relative,
                "title": str(data.get("title") or path.parent.name),
                "statuses": statuses,
            }
        )
    return releases, errors


def report(releases: list[dict]) -> str:
    counts = {
        field: Counter(item["statuses"][field] for item in releases)
        for field in FIELDS
    }
    lines = [
        "# Release Metadata Audit",
        "",
        "Generated by `python3 scripts/audit-release-metadata.py`.",
        "",
        f"- Release pages audited: {len(releases)}",
        "- Canonical taxonomy fields: `labels`, `producers`, `genres`, `tags`",
        "- `legacy` means metadata is present under an unsupported singular "
        "taxonomy field and will render as plain text rather than a safe link.",
        "- `missing` and `empty` require editorial review; `unavailable` is an "
        "explicitly reviewed exception.",
        "",
        "## Summary",
        "",
        "| Field | Canonical and linkable | Legacy | Missing | Empty | Unavailable |",
        "| --- | ---: | ---: | ---: | ---: | ---: |",
    ]
    for field in FIELDS:
        field_counts = counts[field]
        lines.append(
            f"| {field} | {field_counts['linkable']} | "
            f"{field_counts['legacy']} | {field_counts['missing']} | "
            f"{field_counts['empty']} | {field_counts['unavailable']} |"
        )

    lines.extend(["", "## Editorial Review", ""])
    unresolved = [
        item
        for item in releases
        if any(
            status in {"legacy", "missing", "empty"}
            for status in item["statuses"].values()
        )
    ]
    if unresolved:
        for item in unresolved:
            details = ", ".join(
                f"{field}: {status}"
                for field, status in item["statuses"].items()
                if status in {"legacy", "missing", "empty"}
            )
            lines.append(f"- [{item['title']}](../{item['path']}): {details}")
    else:
        lines.append("- None")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--content", type=Path, default=DEFAULT_CONTENT)
    parser.add_argument("--report", type=Path, default=DEFAULT_REPORT)
    parser.add_argument("--check-report", action="store_true")
    args = parser.parse_args()

    releases, errors = audit(args.content)
    rendered = report(releases)
    if args.check_report:
        current = (
            args.report.read_text(encoding="utf-8") if args.report.exists() else ""
        )
        if current != rendered:
            errors.append(
                f"{args.report}: audit report is stale; run this script without "
                "--check-report"
            )
    else:
        args.report.parent.mkdir(parents=True, exist_ok=True)
        args.report.write_text(rendered, encoding="utf-8")

    for error in errors:
        print(f"ERROR: {error}")
    print(f"Audited Release Details metadata for {len(releases)} releases.")
    return 1 if errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
