#!/usr/bin/env python3
"""Validate release types and write the catalogue audit report."""

from __future__ import annotations

import argparse
import re
from collections import Counter
from pathlib import Path

import yaml


ROOT = Path(__file__).parents[1]
DEFAULT_CONTENT = ROOT / "src/content/releases"
DEFAULT_TYPES = ROOT / "src/data/release-types.yaml"
DEFAULT_REPORT = ROOT / "reports/release-type-audit.md"


def front_matter(path: Path) -> dict:
    text = path.read_text(encoding="utf-8-sig")
    match = re.match(r"(?s)^---\s*\n(.*?)\n---(?:\s*\n|$)", text)
    if not match:
        return {}
    parsed = yaml.safe_load(match.group(1)) or {}
    return parsed if isinstance(parsed, dict) else {}


def allowed_types(path: Path) -> set[str]:
    parsed = yaml.safe_load(path.read_text(encoding="utf-8")) or []
    if not isinstance(parsed, list) or not all(
        isinstance(value, str) and value.strip() for value in parsed
    ):
        raise ValueError(f"{path} must contain a YAML list of release types")
    return {value.strip() for value in parsed}


def audit(content_root: Path, types_path: Path) -> tuple[list[dict], list[str]]:
    allowed = allowed_types(types_path)
    releases: list[dict] = []
    errors: list[str] = []

    for path in sorted(content_root.rglob("index.md")):
        data = front_matter(path)
        try:
            relative = path.relative_to(ROOT).as_posix()
        except ValueError:
            relative = path.relative_to(content_root).as_posix()
        canonical = str(data.get("releaseType") or "").strip()
        aliases = {
            key: str(data.get(key) or "").strip()
            for key in ("release_type", "type")
            if str(data.get(key) or "").strip()
        }
        review = data.get("releaseTypeReview") is True

        status = "valid"
        value = canonical
        if not canonical:
            status = "review" if review else "missing"
            if aliases:
                status = "legacy"
                value = next(iter(aliases.values()))
        elif canonical not in allowed:
            status = "invalid"

        if status == "missing":
            errors.append(f"{relative}: releaseType is missing or empty")
        elif status == "invalid":
            errors.append(f"{relative}: unrecognised releaseType {canonical!r}")
        elif status == "legacy":
            errors.append(
                f"{relative}: use canonical releaseType instead of "
                f"{', '.join(aliases)}"
            )

        releases.append(
            {
                "path": relative,
                "title": str(data.get("title") or path.parent.name),
                "type": value,
                "status": status,
            }
        )
    return releases, errors


def report(releases: list[dict]) -> str:
    counts = Counter(item["status"] for item in releases)
    type_counts = Counter(
        item["type"] for item in releases if item["status"] == "valid"
    )
    lines = [
        "# Release Type Audit",
        "",
        "Generated by `python3 scripts/audit-release-types.py`.",
        "",
        f"- Release pages audited: {len(releases)}",
        f"- Valid canonical release types: {counts['valid']}",
        f"- Explicitly flagged for manual review: {counts['review']}",
        f"- Missing, invalid, or legacy fields: "
        f"{counts['missing'] + counts['invalid'] + counts['legacy']}",
        "",
        "## Valid Types",
        "",
    ]
    lines.extend(f"- {name}: {count}" for name, count in sorted(type_counts.items()))
    lines.extend(["", "## Manual Review", ""])
    reviews = [item for item in releases if item["status"] == "review"]
    if reviews:
        lines.extend(
            f"- [{item['title']}](../{item['path']}): release type not verified"
            for item in reviews
        )
    else:
        lines.append("- None")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--content", type=Path, default=DEFAULT_CONTENT)
    parser.add_argument("--types", type=Path, default=DEFAULT_TYPES)
    parser.add_argument("--report", type=Path, default=DEFAULT_REPORT)
    parser.add_argument("--check-report", action="store_true")
    args = parser.parse_args()

    releases, errors = audit(args.content, args.types)
    rendered = report(releases)
    if args.check_report:
        current = (
            args.report.read_text(encoding="utf-8") if args.report.exists() else ""
        )
        if current != rendered:
            errors.append(
                f"{args.report}: audit report is stale; run this script without "
                "--check-report"
            )
    else:
        args.report.parent.mkdir(parents=True, exist_ok=True)
        args.report.write_text(rendered, encoding="utf-8")

    for error in errors:
        print(f"ERROR: {error}")
    print(
        f"Audited {len(releases)} releases; "
        f"{sum(item['status'] == 'review' for item in releases)} need manual review."
    )
    return 1 if errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
