name: Lint Markdown

on:
  push:
  pull_request:

jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout source using v4.1.1
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Lint Markdown using v22.0.0
        uses: DavidAnson/markdownlint-cli2-action@ce4853d43830c74c1753b39f3cf40f71c2031eb9
        with:
          globs: |
            **/*.md
            !src/themes/**
