name: LintShowNotes

on:
  push:
    branches:
      - main
    paths:
      - "**/content/**/001*"
  pull_request:
    paths:
      - "**/content/**/001*"

jobs:
  lintShowNotes:
    runs-on: ubuntu-latest
    permissions:
      statuses: write

    steps:
      - name: Checkout source using v4.1.1
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Setup Node using v4.0.2
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
        with:
          node-version: 16.x
      - name: Lint show notes
        run: |
          npm i -g markdownlint-cli2
          markdownlint-cli2 "**/content/**/001*"
