name: Lint Markdown

on:
  push:
  pull_request:

jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout source using v4.1.1
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Lint Markdown using v22.0.0
        uses: DavidAnson/markdownlint-cli2-action@21c1be1b93ad9ed58fa840aacc3f279cde2a72ff # v22.0.0
        with:
          globs: |
            **/*.md
            !src/themes/**
