name: Lint Markdown

on:
  push:
  pull_request:

jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout source using v4.1.1
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Lint Markdown using v22.0.0
        uses: DavidAnson/markdownlint-cli2-action@6b51ade7a9e4a75a7ad929842dd298a3804ebe8b
        with:
          globs: |
            **/*.md
            !src/themes/**
