name: LintMarkdown

on:
  push:
    branches:
      - main
    paths:
      - "**/*.md"
  pull_request:
    paths:
      - "**/*.md"

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      statuses: write

    steps:
      - uses: actions/checkout@v4.1.1
      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
        with:
          node-version: 16.x
      - name: Lint markdown files
        run: |
          npm i -g markdownlint-cli2
          markdownlint-cli2 "**/*.md"
